create extension if not exists pgcrypto;

create table if not exists whatsapp_connection_status (
  id text primary key,
  status text default 'initializing',
  service text default 'M-JARVIS WhatsApp Engine',
  is_connected boolean default false,
  connection_state text default 'initializing',
  reconnect_attempts integer default 0,
  last_connected_at timestamptz,
  last_disconnected_at timestamptz,
  last_error text,
  engine_url text,
  metadata jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists whatsapp_messages (
  id bigint generated by default as identity primary key,
  sender_number text not null,
  sender_name text,
  message_text text,
  jarvis_reply text,
  message_type text default 'text',
  direction text default 'incoming',
  metadata jsonb default '{}'::jsonb,
  timestamp timestamptz default now(),
  is_read boolean default false
);

alter table whatsapp_messages add column if not exists sender_name text;
alter table whatsapp_messages add column if not exists message_text text;
alter table whatsapp_messages add column if not exists jarvis_reply text;
alter table whatsapp_messages add column if not exists message_type text default 'text';
alter table whatsapp_messages add column if not exists direction text default 'incoming';
alter table whatsapp_messages add column if not exists metadata jsonb default '{}'::jsonb;
alter table whatsapp_messages add column if not exists timestamp timestamptz default now();
alter table whatsapp_messages add column if not exists is_read boolean default false;

create table if not exists jarvis_interactions (
  id uuid primary key default gen_random_uuid(),
  sender_number text not null,
  sender_name text,
  user_message text,
  ai_reply text,
  provider text,
  response_time_ms integer,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists whatsapp_status_updates (
  id uuid primary key default gen_random_uuid(),
  contact_number text,
  status_text text,
  media_url text,
  metadata jsonb default '{}'::jsonb,
  captured_at timestamptz default now()
);

create table if not exists whatsapp_groups (
  group_jid text primary key,
  group_name text,
  participant_count integer default 0,
  metadata jsonb default '{}'::jsonb,
  last_seen_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists jarvis_training_rules (
  id uuid primary key default gen_random_uuid(),
  keyword text not null unique,
  response text not null,
  is_active boolean default true,
  source text default 'manual',
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_whatsapp_messages_timestamp on whatsapp_messages(timestamp desc);
create index if not exists idx_whatsapp_messages_sender on whatsapp_messages(sender_number);
create index if not exists idx_whatsapp_messages_is_read on whatsapp_messages(is_read);
create index if not exists idx_whatsapp_connection_status_updated_at on whatsapp_connection_status(updated_at desc);
create index if not exists idx_jarvis_interactions_sender on jarvis_interactions(sender_number, created_at desc);
create index if not exists idx_whatsapp_status_updates_captured_at on whatsapp_status_updates(captured_at desc);
create index if not exists idx_whatsapp_groups_last_seen_at on whatsapp_groups(last_seen_at desc);

alter table whatsapp_messages replica identity full;
alter table whatsapp_connection_status replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table whatsapp_messages;
    exception
      when duplicate_object then null;
    end;

    begin
      alter publication supabase_realtime add table whatsapp_connection_status;
    exception
      when duplicate_object then null;
    end;
  end if;
end $$;
